build:
  environment:
    node: '8.9.4'
  dependencies:
    override:

#      # Install expect if not present
#      - command -v expect &>/dev/null || command -v apt-get &>/dev/null
#      - command -v expect &>/dev/null || sudo apt-get -y update
#      - command -v expect &>/dev/null || sudo apt-get -y install expect
#      - command -v expect
#
#      # npm dependencies
#      - npm rebuild
      - npm install

  tests:
    override:
      - command: 'npm test'
        coverage:
          file: 'coverage/clover.xml'
          format: 'clover'
checks:
  javascript:
    code_rating: true

filter:
  excluded_paths:
    - "*.min.js" # Don't analyze minified files
